-- ============================================================================
-- Sentinel UEBA — esquema SOC (Supabase / Postgres)
-- Tablas: organizations, profiles, daily_scores, alerts, alert_events, audit_log
-- ============================================================================

create extension if not exists "pgcrypto";

-- Organizaciones (multi-tenant). CERT r4.2 = una organización demo.
create table if not exists public.organizations (
  id   uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

-- Perfil de usuario (1:1 con auth.users). Define rol y organización.
create table if not exists public.profiles (
  id              uuid primary key references auth.users (id) on delete cascade,
  full_name       text,
  role            text not null default 'client'
                    check (role in ('analyst', 'admin', 'client')),
  organization_id uuid references public.organizations (id),
  created_at      timestamptz not null default now()
);

-- Serie diaria de riesgo por empleado (para los timelines de investigación).
create table if not exists public.daily_scores (
  id              bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations (id),
  user_cert       text not null,        -- empleado CERT, p.ej. 'ACM2278'
  day             date not null,
  risk            numeric(5,2) not null, -- 0-100
  detector        text not null,
  threat_type     text,
  scenario        int,                  -- ground truth (solo interno)
  is_insider      boolean default false -- ground truth (solo interno)
);

-- Cola de alertas (núcleo del ticketing): 1 por empleado-pico sobre umbral.
create table if not exists public.alerts (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id),
  user_cert       text not null,
  peak_day        date not null,
  risk            numeric(5,2) not null,
  detector        text not null,
  threat_type     text,
  department      text,
  role_cert       text,
  scenario        int,                  -- ground truth (solo interno)
  is_insider      boolean default false,-- ground truth (solo interno)
  status          text not null default 'new'
                    check (status in ('new','investigating','escalated','closed','false_positive')),
  assigned_to     uuid references public.profiles (id),
  reasons         jsonb,                -- conductas destacadas [{label,value,avg}]
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (organization_id, user_cert)
);

-- Eventos de investigación (timeline + cambios de estado/asignación/notas).
create table if not exists public.alert_events (
  id         uuid primary key default gen_random_uuid(),
  alert_id   uuid not null references public.alerts (id) on delete cascade,
  author     uuid references public.profiles (id),
  kind       text not null
               check (kind in ('status_change','note','assignment','acknowledge')),
  payload    jsonb,
  note       text,
  created_at timestamptz not null default now()
);

-- Auditoría: "quién investigó a quién" (GDPR / ISO 27001 / SOC2).
create table if not exists public.audit_log (
  id               uuid primary key default gen_random_uuid(),
  actor            uuid references public.profiles (id),
  action           text not null,
  target_alert     uuid references public.alerts (id) on delete set null,
  target_user_cert text,
  created_at       timestamptz not null default now()
);

-- Índices de consulta frecuente.
create index if not exists idx_daily_scores_user
  on public.daily_scores (organization_id, user_cert, day);
create index if not exists idx_alerts_org_status
  on public.alerts (organization_id, status);
create index if not exists idx_alerts_risk
  on public.alerts (organization_id, risk desc);
create index if not exists idx_alert_events_alert
  on public.alert_events (alert_id, created_at);
create index if not exists idx_audit_created
  on public.audit_log (created_at desc);
