-- ============================================================================
-- Sentinel UEBA — tabla de EVIDENCIA forense por alerta
-- Eventos crudos del día pico (acceso, USB, ficheros, correo). Solo interno.
-- Se puebla con scripts/build_evidence.py desde los logs CERT r4.2.
-- ============================================================================

create table if not exists public.evidence (
  id              bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations (id),
  user_cert       text not null,
  day             date not null,
  ts              timestamptz not null,
  kind            text not null check (kind in ('file_copy','usb','email','logon')),
  summary         text not null,
  detail          jsonb,
  severity        text not null default 'info' check (severity in ('info','warn','crit'))
);

create index if not exists idx_evidence_user_day
  on public.evidence (organization_id, user_cert, day, ts);

alter table public.evidence enable row level security;

-- Solo roles internos (analista/admin) de la organización ven la evidencia.
drop policy if exists evidence_read on public.evidence;
create policy evidence_read on public.evidence
  for select using (public.is_internal() and organization_id = public.auth_org());
